Install 'faiss-cpu' library

In [1]:
!pip install faiss-cpu


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
   ------- -------------------------------- 3.7/18.9 MB 47.9 MB/s eta 0:00:01
   ------------------------------------ --- 17.3/18.9 MB 61.7 MB/s eta 0:00:01
   ---------------------------------------- 18.9/18.9 MB 58.7 MB/s  0:00:00



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Import faiss   and numpy libraries

In [2]:
# place your code here
import faiss
import numpy as np

Using the rand() function from numpy, create a set of
100 000 numeric vectors of length 768 with random numbers as elements.   Store a set of numeric vectors in the 'data' variable.

In [8]:
# place your code here
data = np.random.rand(100_000, 768)
print(data)

[[0.21569143 0.90397989 0.07818287 ... 0.32622846 0.55663266 0.68399681]
 [0.95995089 0.90087356 0.34053696 ... 0.05862878 0.14814241 0.75304709]
 [0.88890804 0.32580991 0.08150417 ... 0.90455681 0.09807064 0.38898405]
 ...
 [0.76207951 0.32408636 0.69518493 ... 0.29856482 0.67214653 0.47909317]
 [0.78205578 0.59190099 0.73701543 ... 0.14649857 0.08455216 0.68627449]
 [0.34167693 0.39539338 0.35689318 ... 0.80783784 0.84484754 0.84713052]]


Using the simple, very accurate (but not too fast) 'IndexFlatL2()' method from the faiss library, create an index for vectors of length 768 and store its object in the variable 'index'.

In [13]:
# place your code here

index = faiss.IndexFlatL2(768)

Using the 'assert' statement and the 'is_trained' property of the 'index' object to check if the index is created.

In [14]:
# place your code here
print(index.is_trained)

True


Index your vector set using the .add() method of the 'index' object, calling the method with the 'data' variable as an argument.

In [15]:
# place your code here
index.add(data)


Using the 'index' property of the 'ntotal' object, check how many vectors are contained at the index.

In [16]:
# place your code here
index.ntotal

100000

Using the rand() function from numpy, create a  numeric vectors of length 768 with random numbers as elements. Store a numeric vectors in the 'query' variable.

In [19]:
# place your code here
query = np.random.rand(1, 768)

Search the created index for similar vectors for the 'query' vector. Use the .search(query, n) method of the 'index' object with two arguments: the query vector and the number of similar vectors to search for.  
Store the search results in two variables: D (data) and I (indixes)  using multiple assignment.

In [21]:
# place your code here
k = 5
D, I = index.search(query, k)

Print the results

In [22]:
# place your code here
print(D)

[[106.546326 107.11608  108.80385  109.252884 109.48535 ]]


In [23]:
# place your code here
print(I)

[[97751 48896  6030 31288 83815]]
